In [1]:
import os

import pandas as pd
import numpy as np

import functions.cnn_helpers as help_funcs

# DNA MERFISH data (Su et al. 2020)

## Read distance info and save as arrays

In [2]:
dist_data = pd.read_csv('../data/Su_2020/selected_structures_1000_nm_thr.tsv', sep='\t')
transc_data = pd.read_csv('../data/Su_2020/transcriptional_data_1000_nm_thr.tsv', sep='\t')

dataset = pd.merge(dist_data, transc_data.iloc[:, :2], how='left', on='Chromosome copy number')

n_loci = 38

### Iterate through all structures and save them as an image

In [3]:
for id, row in dataset.iterrows():
    
    struct_id = int(row['Chromosome copy number'])
    state = int(row['BACH1'])
    if state == 0:
        state_save = 'inactive'
    else:
        state_save = 'active'
    
    dists = row.iloc[1 : -1]
    
    locus_i = 0
    dist_i = np.zeros((n_loci, n_loci))
    
    for i in range(0, n_loci):
        for j in range(i + 1, n_loci):
            dist_i[i,j] = dists.iloc[locus_i]
            
            locus_i += 1
    
    dist_i = dist_i + dist_i.T
    
    
    dist_i = pd.DataFrame(dist_i)
    dist_i.to_csv(f"../data/Su_2020/distance_maps/{state_save}/structure_{struct_id}.tsv", sep='\t', header = False, index=False)

## Create splits and save them before (.png) and after (.tsv) normalization

In [ ]:
help_funcs.kfold_splits(src_folder = '../data/Su_2020/distance_maps/', dst_folder = '../data/Su_2020/CNN_splits')

FileNotFoundError: [Errno 2] No such file or directory: '../data/distance_maps/'

In [29]:
samples = []

# Subfolders are class labels
classes = sorted(
    [
        class_i
        for class_i in os.listdir('../data/CNN_splits_zscore/fold_0/test')
        if os.path.isdir(os.path.join('../data/CNN_splits_zscore/fold_0/test', class_i))
    ],
    reverse=True,
)
class_to_idx = {cls: idx for idx, cls in enumerate(classes)}

for label in os.listdir('../data/CNN_splits_zscore/fold_0/test'):
    class_dir = os.path.join('../data/CNN_splits_zscore/fold_0/test', label)
    if not os.path.isdir(class_dir):
        continue

    for fname in os.listdir(class_dir):
        if fname.endswith(".tsv"):
            path = os.path.join(class_dir, fname)
            samples.append((path, int(class_to_idx[label])))

In [32]:
samples

[('../data/CNN_splits_zscore/fold_0/test/inactive/structure_1413.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_2126.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_6432.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_8379.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_1177.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_3006.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_9271.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_1836.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_10542.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_8755.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_11476.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_2091.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_11675.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_8807.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_8185.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_628.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_172.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_6433.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_402.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_1374.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_10179.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_8391.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_11930.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_3788.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_1835.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_2482.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_9448.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_2509.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_986.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_4622.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_10794.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_6592.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_2093.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_4435.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_10030.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_9887.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_1565.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_10024.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_8970.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_3825.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_3158.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_5273.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_10391.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_8179.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_11716.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_9717.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_11272.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_4569.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_7060.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_11262.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_405.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_613.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_161.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_808.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_7306.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_3174.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_11896.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_7851.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_9698.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_8236.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_2294.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_8020.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_766.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_2862.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_9089.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_3759.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_11077.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_10369.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_10396.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_9300.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_3177.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_8750.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_10547.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_3163.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_8963.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_9499.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_8552.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_9671.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_11472.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_7304.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_11670.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_6608.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_8619.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_2863.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_7927.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_7714.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_2678.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_8468.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_9789.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_7940.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_9574.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_1841.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_1699.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_4118.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_6914.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_12120.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_7835.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_7612.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_11831.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_10508.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_2554.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_8737.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_11158.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_10326.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_8469.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_10642.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_10126.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_2813.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_5826.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_10481.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_8735.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_11172.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_1922.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_43.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_10720.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_12137.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_2768.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_4319.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_11364.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_9615.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_10906.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_8278.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_11167.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_8720.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_1857.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_8683.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_10696.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_2147.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_9006.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_12042.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_7946.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_11771.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_3739.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_10533.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_2023.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_6523.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_2989.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_7629.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_8240.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_7826.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_10080.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_275.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_12127.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_5017.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_10532.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_1073.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_10240.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_8692.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_1113.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_4043.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_11770.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_10136.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_9003.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_9983.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_7789.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_2424.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_8069.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_1065.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_1717.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_934.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_4337.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_5997.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_10732.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_7616.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_263.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_7819.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_9148.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_5000.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_8524.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_8040.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_7575.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_5410.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_7752.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_9031.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_6470.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_469.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_11232.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_5186.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_2831.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_6100.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_4071.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_8850.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_2212.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_9145.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_11420.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_9804.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_2945.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_10925.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_9192.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_3482.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_1281.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_10298.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_6707.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_3119.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_11970.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_8662.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_8104.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_1646.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_4299.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_332.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_3247.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_3279.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_9973.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_8660.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_1877.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_1042.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_5754.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_1532.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_4338.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_11437.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_9620.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_10099.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_7803.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_8259.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_3330.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_11191.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_9392.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_3867.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_7368.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_2562.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_5557.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_11754.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_10304.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_8675.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_8107.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_5190.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_10106.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_2176.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_11546.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_3526.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_1641.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_1655.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_5209.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_1709.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_9369.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_7436.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_8936.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_269.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_5023.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_2994.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_72.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_268.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_8076.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_8738.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_6067.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_5397.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_10301.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_2605.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_9034.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_9020.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_7743.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_2377.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_3733.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_9418.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_8712.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_8935.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_7390.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_10049.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_11394.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_10706.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_3336.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_6514.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_8539.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_11183.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_8713.tsv', 0),
 ('../data/CNN_splits_zscore/fold_0/test/inactive/structure_9431.tsv', 0),

# ORCA data (Mateo et al. 2020)

## Read distance info and save as arrays

In [59]:
dist_data = pd.read_csv('../data/Mateo_2019/selected_structures.tsv', sep='\t')
transc_data = pd.read_csv('../data/Mateo_2019/transcriptional_data.tsv', sep='\t')

dataset = pd.merge(dist_data, transc_data.iloc[:, :2], how='left', on='cellNumber')

n_loci = 52

In [60]:
dataset

,cellNumber,1-2,1-3,1-4,1-5,1-6,1-7,1-8,1-9,1-10,...,48-50,48-51,48-52,49-50,49-51,49-52,50-51,50-52,51-52,Abd-A_Intron
0,2.0,244.073929,156.705215,227.523438,298.594910,284.360779,319.927277,374.712128,263.243683,307.865479,...,158.210205,205.904953,89.207565,190.698318,243.541779,129.752823,129.892990,114.832573,134.459518,0
1,3.0,262.981628,149.599136,223.714142,298.312103,284.214844,319.122009,373.181580,263.169769,307.152435,...,148.777985,164.663910,56.323582,173.666397,188.108734,68.595428,74.033485,109.178902,135.220947,0
2,13.0,124.413574,62.232868,257.654388,220.720657,246.008240,441.668243,756.308289,263.075958,348.715790,...,359.092010,261.710297,175.725861,371.491577,260.087463,185.764450,168.830246,186.105453,112.900101,0
3,19.0,69.282951,138.565903,207.848846,443.208252,238.614304,273.902191,251.590515,290.168945,330.703491,...,247.873260,371.809601,341.640991,123.936684,247.873001,247.677017,123.936325,191.545700,206.775375,0
4,20.0,140.162399,280.324799,189.418167,158.130585,214.382599,314.234467,237.620895,364.475861,219.858322,...,26.428993,203.600006,384.076782,189.821518,270.037781,418.468781,180.703522,361.407043,180.703522,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2289,54296.0,100.621590,128.352631,286.576843,248.898636,218.128952,296.315460,379.651459,443.508423,539.908630,...,162.532089,142.924255,298.095154,138.703461,180.236008,301.980347,264.441345,421.862579,191.273575,1
2290,54298.0,90.672394,92.193672,265.648987,275.079193,197.236557,120.854897,159.037033,203.947113,274.588165,...,250.285370,146.688385,377.458160,144.669647,342.024048,612.465637,284.677338,569.354797,284.677460,1
2291,54310.0,223.677322,447.354645,531.770569,423.878387,492.909790,394.430939,300.274506,216.164169,359.377045,...,171.912140,257.868195,343.824280,85.956055,171.912109,257.868195,85.956055,171.912140,85.956085,1
2292,54333.0,45.941437,91.882996,295.733276,1146.179077,871.597900,598.217834,329.046478,502.175598,409.138489,...,160.223740,155.931351,269.772308,62.877518,141.710861,293.308624,157.828156,315.656555,157.828400,1
2293,54358.0,179.968307,359.936523,374.645172,417.090302,377.901825,398.354401,478.556061,327.218567,224.126022,...,156.117645,147.301254,146.064972,114.419899,99.215271,94.381157,34.002762,68.005524,34.002762,0

In [62]:
transc_data

       cellNumber  Abd-A_Intron
0               1             0
1               2             0
2               3             0
3               4             0
4               5             0
...           ...           ...
54344       54360             1
54345       54361             0
54346       54362             0
54347       54363             0
54348       54364             1

[54349 rows x 2 columns]

### Iterate through all structures and save them as an image

In [51]:
for id, row in dataset.iterrows():
    
    struct_id = int(row['cellNumber'])
    state = int(row['Abd-A_Intron'])
    if state == 0:
        state_save = 'inactive'
    else:
        state_save = 'active'
    
    dists = row.iloc[1 : -1]
    
    locus_i = 0
    dist_i = np.zeros((n_loci, n_loci))
    
    for i in range(0, n_loci):
        for j in range(i + 1, n_loci):
            dist_i[i,j] = dists.iloc[locus_i]
            
            locus_i += 1
    
    dist_i = dist_i + dist_i.T
    
    
    dist_i = pd.DataFrame(dist_i)
    dist_i.to_csv(f"../data/Mateo_2019/distance_maps/{state_save}/structure_{struct_id}.tsv", sep='\t', header = False, index=False)

## Create splits and save them before (.png) and after (.tsv) normalization

In [56]:
help_funcs.kfold_splits(src_folder = '../data/Mateo_2019/distance_maps/', dst_folder = '../data/Mateo_2019/CNN_splits')

Creating fold 1/5...
Train size: 1376, Validation size: 459, Test size: 459
Creating fold 2/5...
Train size: 1376, Validation size: 459, Test size: 459
Creating fold 3/5...
Train size: 1376, Validation size: 459, Test size: 459
Creating fold 4/5...
Train size: 1376, Validation size: 459, Test size: 459
Creating fold 5/5...
Train size: 1376, Validation size: 459, Test size: 459

In [57]:
samples = []

# Subfolders are class labels
classes = sorted(
    [
        class_i
        for class_i in os.listdir('../data/Mateo_2019/CNN_splits_zscore/fold_0/test')
        if os.path.isdir(os.path.join('../data/Mateo_2019/CNN_splits_zscore/fold_0/test', class_i))
    ],
    reverse=True,
)
class_to_idx = {cls: idx for idx, cls in enumerate(classes)}

for label in os.listdir('../data/Mateo_2019/CNN_splits_zscore/fold_0/test'):
    class_dir = os.path.join('../data/Mateo_2019/CNN_splits_zscore/fold_0/test', label)
    if not os.path.isdir(class_dir):
        continue

    for fname in os.listdir(class_dir):
        if fname.endswith(".tsv"):
            path = os.path.join(class_dir, fname)
            samples.append((path, int(class_to_idx[label])))

In [58]:
samples

[('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_1361.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_34755.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_43287.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_41484.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_17403.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_39067.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_10556.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_35701.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_50199.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_9885.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_11489.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_20696.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_51443.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_33588.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_31162.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_13466.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_12020.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_40941.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_45434.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_14848.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_2521.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_15411.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_38965.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_19968.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_37470.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_45780.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_53848.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_18849.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_788.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_2246.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_29074.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_2871.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_53055.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_2646.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_19602.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_21404.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_2861.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_53247.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_51444.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_21835.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_13717.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_23818.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_34380.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_52950.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_41938.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_53680.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_2915.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_32519.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_30468.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_11868.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_10545.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_36421.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_38418.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_5470.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_42439.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_34752.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_33983.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_46477.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_7715.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_40589.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_19205.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_34368.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_17599.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_20320.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_48088.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_46700.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_10552.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_19576.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_2532.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_51491.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_51485.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_8157.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_44711.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_33599.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_41899.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_29072.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_8433.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_19303.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_17474.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_46029.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_13799.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_41791.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_21298.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_22975.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_2964.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_2780.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_39429.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_2756.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_3460.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_45079.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_3886.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_41800.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_10483.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_41141.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_14381.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_22182.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_35173.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_48013.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_2581.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_18368.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_2768.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_2740.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_38090.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_50488.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_29188.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_32594.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_2543.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_46163.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_45697.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_12056.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_14379.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_45687.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_18769.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_14621.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_35189.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_35610.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_41754.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_50881.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_6047.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_40338.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_16195.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_14219.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_2750.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_20354.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_2585.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_12325.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_13826.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_20552.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_47293.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_43591.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_29979.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_53958.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_39565.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_23059.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_49323.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_10530.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_46004.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_13978.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_53186.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_30409.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_32550.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_24333.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_2974.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_42707.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_45530.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_21897.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_8685.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_41811.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_13819.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_20579.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_50075.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_12093.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_17882.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_45652.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_24262.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_19322.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_13800.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_31445.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_46008.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_52928.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_40653.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_14202.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_39353.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_5794.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_34887.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_34110.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_39178.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_24840.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_40478.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_23083.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_50535.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_454.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_654.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_5378.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_13630.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_30957.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_2365.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_16172.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_4304.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_33899.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_27153.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_18837.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_12249.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_18016.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_13625.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_42442.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_19452.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_7963.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_13355.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_45107.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_49701.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_44209.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_52443.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_17692.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_42308.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_21693.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_49249.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_5355.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_44143.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_46973.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_24338.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_2956.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_13967.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_5552.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_11143.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_19331.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_39977.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_39552.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_14403.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_49710.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_23293.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_13350.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_13422.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_17108.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_39550.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_30206.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_9550.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_2439.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_40520.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_41010.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_48222.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_2767.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_58.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_15643.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_zscore/fold_0/test/inactive/structure_1285.tsv',
  0),